name: Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - name: Install haxelibs
      run: haxelib install format --always && haxelib install bin-packing --always && haxelib install tink_cli --always && haxelib install hxcpp --always
    - name: Compile
      run: .\run.bat
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build-windows
        path: |
          .\build\AssetPacker.exe
